import { handle, ok } from "@/lib/api";
import { assertCsrf, requirePlatformAdmin } from "@/lib/auth";
import { multiAgentComplete, type ChatMessage } from "@/lib/ai/provider";
import { getPlatformSecret, listPlatformSecretMetadata } from "@/lib/platform-secrets";

export const dynamic = "force-dynamic";
const NVIDIA_TTS_URL = "https://877104f7-e885-42b9-8de8-f6e4c6303969.invocation.api.nvcf.nvidia.com/v1/audio/synthesize";

async function resolveSecret(name: "GROQ_API_KEY" | "OPENROUTER_API_KEY" | "NVIDIA_API_KEY") { return (await getPlatformSecret(name)) ?? process.env[name] ?? null; }
async function requiredSecret(name: "GROQ_API_KEY" | "OPENROUTER_API_KEY") { const value = await resolveSecret(name); if (value) return value; const stored = (await listPlatformSecretMetadata()).some((item) => item.key === name); throw new Error(stored ? `${name} exists in VO Settings but cannot be decrypted in this deployment. Re-save the key once in Settings.` : `${name} is not configured in VO → Settings.`); }
function languageFor(text: string) { return /[\u0600-\u06FF]/.test(text) ? "ar-MSA" : "en-US"; }
async function nvidiaTts(text: string, key: string) { const language = languageFor(text); const voice = language === "ar-MSA" ? "Magpie-Multilingual.AR-MSA.Alya" : "Magpie-Multilingual.EN-US.Aria"; const form = new FormData(); form.append("text", text.slice(0, 5000)); form.append("language", language); form.append("voice", voice); form.append("encoding", "LINEAR_PCM"); form.append("sample_rate_hz", "44100"); const response = await fetch(NVIDIA_TTS_URL, { method: "POST", headers: { Authorization: `Bearer ${key}` }, body: form, cache: "no-store" }); if (!response.ok) throw new Error(`NVIDIA TTS failed (${response.status}): ${await response.text()}`); const bytes = Buffer.from(await response.arrayBuffer()); return { audio: `data:audio/wav;base64,${bytes.toString("base64")}`, engine: "NVIDIA Magpie Multilingual" }; }
async function openRouterTts(text: string, key: string) { const model = process.env.GARVEX_TTS_MODEL || "mistralai/voxtral-mini-tts-2603"; const voice = process.env.GARVEX_TTS_VOICE || "en_paul_neutral"; const response = await fetch("https://openrouter.ai/api/v1/audio/speech", { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ model, voice, input: text.slice(0, 8000), response_format: "mp3" }), cache: "no-store" }); if (!response.ok) throw new Error(`OpenRouter TTS failed (${response.status}): ${await response.text()}`); const contentType = response.headers.get("content-type")?.split(";")[0] ?? "audio/mpeg"; if (!contentType.startsWith("audio/")) throw new Error(`Unexpected TTS response: ${contentType}`); return { audio: `data:${contentType};base64,${Buffer.from(await response.arrayBuffer()).toString("base64")}`, engine: "OpenRouter TTS" }; }

export async function POST(request: Request) { return handle(async () => { const user = await requirePlatformAdmin(); await assertCsrf(user); const form = await request.formData(); const file = form.get("audio"); if (!(file instanceof File)) throw new Error("audio file is required"); if (file.size > 25 * 1024 * 1024) throw new Error("Audio file is too large (max 25 MB)");
  const groqKey = await requiredSecret("GROQ_API_KEY"); const transcription = new FormData(); transcription.append("file", file, file.name || "voice.webm"); transcription.append("model", "whisper-large-v3-turbo"); transcription.append("response_format", "json"); const stt = await fetch("https://api.groq.com/openai/v1/audio/transcriptions", { method: "POST", headers: { Authorization: `Bearer ${groqKey}` }, body: transcription, cache: "no-store" }); if (!stt.ok) throw new Error(`Speech-to-text failed (${stt.status}): ${await stt.text()}`); const sttData = await stt.json() as { text?: string }; const text = String(sttData.text ?? "").trim(); if (!text) throw new Error("No speech was detected.");
  const messages: ChatMessage[] = [{ role: "system", content: "You are Garvex Voice. Answer naturally, confidently, and concisely. Preserve the user's language. This voice channel is read-only unless the user explicitly asks for a supported Build & Fix operation. Never claim an action happened unless the system actually performed it." }, { role: "user", content: text }]; const result = await multiAgentComplete(messages, { strategy: "single", timeoutMs: 4500 });
  const nvidiaKey = await resolveSecret("NVIDIA_API_KEY"); const openRouterKey = await resolveSecret("OPENROUTER_API_KEY"); let audio: { audio: string; engine: string } | null = null; let lastError: Error | null = null; if (nvidiaKey) { try { audio = await nvidiaTts(result.text, nvidiaKey); } catch (error) { lastError = error instanceof Error ? error : new Error(String(error)); } } if (!audio && openRouterKey) { try { audio = await openRouterTts(result.text, openRouterKey); } catch (error) { lastError = error instanceof Error ? error : new Error(String(error)); } } if (!audio && lastError) throw lastError; return ok({ transcript: text, answer: result.text, provider: result.provider, model: result.model, workers: result.workers, audio: audio?.audio ?? null, audioEngine: audio?.engine ?? null }); }); }
