"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { MessageResponse } from "@/components/ai-elements/message";

type Provider = { provider: string; model: string; configured: boolean; stored?: number; readable?: number; environment?: boolean; state?: "ready" | "stored-unreadable" | "missing" };
type Worker = { provider: string; model: string; tokensIn: number; tokensOut: number };
type Project = { id: string; name: string; repoFullName: string; liveUrl?: string };
type ChatMessage = { id: string; role: "user" | "assistant"; content: string; mode?: "chat" | "build" | "research" };
type Activity = { id: string; label: string; detail: string; status: "running" | "complete" | "error" };
type WorkspaceTab = "activity" | "code" | "preview" | "files" | "terminal";
const labels: Record<string, string> = { nvidia: "NVIDIA", openrouter: "OpenRouter", mistral: "Mistral", cerebras: "Cerebras", groq: "Groq", kilo: "Kilo", cohere: "Cohere" };
const id = (p: string) => `${p}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const arabic = (s: string) => /[\u0600-\u06FF]/.test(s);

function Orb3D({ size = 120 }: { size?: number }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current;
    if (!canvas) return;
    const gl = canvas.getContext("webgl2", { alpha: true, antialias: true, powerPreference: "high-performance", desynchronized: true });
    if (!gl) return;
    const compile = (type: number, src: string) => { const shader = gl.createShader(type); if (!shader) throw new Error("WebGL shader allocation failed"); gl.shaderSource(shader, src); gl.compileShader(shader); if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(shader) || "WebGL shader error"); return shader; };
    const vs = compile(gl.VERTEX_SHADER, `#version 300 es\nin vec2 p;out vec2 uv;void main(){uv=p*.5+.5;gl_Position=vec4(p,0.,1.);}`);
    const fs = compile(gl.FRAGMENT_SHADER, `#version 300 es\nprecision highp float;in vec2 uv;out vec4 outColor;uniform float t;\nmat2 rot(float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c);}\nfloat map(vec3 p){return length(p)-.63;}\nvec3 normalAt(vec3 p){float e=.0015;return normalize(vec3(map(p+vec3(e,0,0))-map(p-vec3(e,0,0)),map(p+vec3(0,e,0))-map(p-vec3(0,e,0)),map(p+vec3(0,0,e))-map(p-vec3(0,0,e))));}\nvoid main(){vec2 q=uv*2.-1.;float r2=dot(q,q);vec3 bg=vec3(.008,.012,.024);vec3 ro=vec3(0.,0.,2.7),rd=normalize(vec3(q,-2.2));float d=0.,h=0.;vec3 p=ro;bool hit=false;for(int i=0;i<56;i++){p=ro+rd*d;h=map(p);if(h<.001){hit=true;break;}d+=h*.82;if(d>5.)break;}vec3 c=bg+vec3(.02,.05,.16)*exp(-2.2*r2);if(hit){vec3 rp=p;rp.yz=rot(t*.38)*rp.yz;rp.xz=rot(t*.64)*rp.xz;vec3 n=normalAt(p);vec3 l1=normalize(vec3(-.55,.7,1.2));vec3 l2=normalize(vec3(.65,-.15,.55));float d1=max(dot(n,l1),0.);float d2=max(dot(n,l2),0.);float rim=pow(1.-max(dot(n,-rd),0.),2.2);float lon=atan(rp.z,rp.x);float lat=asin(clamp(rp.y/.63,-1.,1.));float mer=0.5+0.5*cos(lon*8.0);float par=0.5+0.5*cos(lat*18.0);float grid=smoothstep(.8,1.,mer*par);vec3 core=vec3(.04,.32,.95);vec3 glow=vec3(.18,.58,1.0);c=core*(.28+1.15*d1)+glow*(.4*d2+.95*rim)+vec3(.35,.8,1.)*grid*.16;}c+=vec3(.05,.2,.8)*exp(-8.*r2);float alpha=hit?1.:smoothstep(1.0,.08,1.-sqrt(r2))*.55;outColor=vec4(c,alpha);}`);
    const program = gl.createProgram(); if (!program) return; gl.attachShader(program, vs); gl.attachShader(program, fs); gl.linkProgram(program); if (!gl.getProgramParameter(program, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(program) || "WebGL program link failed"); gl.useProgram(program);
    const buffer = gl.createBuffer(); if (!buffer) return; gl.bindBuffer(gl.ARRAY_BUFFER, buffer); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]), gl.STATIC_DRAW); const loc = gl.getAttribLocation(program, "p"); gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0); const timeLoc = gl.getUniformLocation(program,"t");
    let raf = 0; let live = true; const draw = (now: number) => { if (!live) return; const dpr = Math.min(window.devicePixelRatio || 1, 3); const w = Math.max(64, Math.floor(size*dpr)); if (canvas.width !== w) { canvas.width=w; canvas.height=w; gl.viewport(0,0,w,w); } gl.clearColor(0,0,0,0); gl.clear(gl.COLOR_BUFFER_BIT); gl.uniform1f(timeLoc, now/1000); gl.drawArrays(gl.TRIANGLES,0,6); raf=requestAnimationFrame(draw); }; raf=requestAnimationFrame(draw);
    return () => { live=false; cancelAnimationFrame(raf); gl.deleteProgram(program); gl.deleteBuffer(buffer); gl.deleteShader(vs); gl.deleteShader(fs); };
  }, [size]);
  return <canvas ref={ref} width={size} height={size} style={{ width:size, height:size, display:"block" }} aria-hidden />;
}

function ProviderPill({ provider }: { provider: Provider }) {
  const state = provider.state ?? (provider.configured ? "ready" : "missing");
  const text = state === "ready" ? "READY" : state === "stored-unreadable" ? "RE-KEY" : "OFF";
  return <div className="garvex-provider-pill"><span className={state === "ready" ? "garvex-agent-dot ready" : state === "stored-unreadable" ? "garvex-agent-dot error" : "garvex-agent-dot idle"}/><div className="min-w-0"><div>{labels[provider.provider] ?? provider.provider}</div><div className="mono truncate">{provider.model}</div></div><span>{text}</span></div>;
}

export function GarvexMaxConsole({ csrf, providers, projects, isPlatformAdmin }: { csrf: string; providers: Provider[]; projects: Project[]; isPlatformAdmin: boolean }) {
  const [prompt,setPrompt]=useState(""); const [mode,setMode]=useState<"chat"|"build"|"research">("chat"); const [busy,setBusy]=useState(false); const [messages,setMessages]=useState<ChatMessage[]>([]); const [workers,setWorkers]=useState<Worker[]>([]); const [failed,setFailed]=useState(0); const [error,setError]=useState<string|null>(null); const [phase,setPhase]=useState("Ready"); const [selectedProjectId,setSelectedProjectId]=useState(""); const [activities,setActivities]=useState<Activity[]>([]); const [tab,setTab]=useState<WorkspaceTab>("activity"); const [files,setFiles]=useState<{path:string;content:string}[]>([]); const [pr,setPr]=useState<string|null>(null); const [media,setMedia]=useState<{kind:"image"|"video";url:string}|null>(null); const [voice,setVoice]=useState(false); const ta=useRef<HTMLTextAreaElement>(null); const recorder=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]);
  const configured=useMemo(()=>providers.filter(p=>p.configured).length,[providers]); const project=useMemo(()=>projects.find(p=>p.id===selectedProjectId),[projects,selectedProjectId]); const credentialProblem=useMemo(()=>providers.filter(p=>p.state === "stored-unreadable"),[providers]);
  useEffect(()=>{try{const x=localStorage.getItem("vo-garvex-history-max");if(x)setMessages(JSON.parse(x));}catch{}},[]); useEffect(()=>{try{localStorage.setItem("vo-garvex-history-max",JSON.stringify(messages.slice(-100)));}catch{}},[messages]);
  const act=(label:string,detail:string,status:"running"|"complete"|"error"="running")=>{const a={id:id("a"),label,detail,status};setActivities(x=>[...x,a]);return a.id;}; const done=(aid:string,detail:string,status:"complete"|"error"="complete")=>setActivities(x=>x.map(a=>a.id===aid?{...a,status,detail}:a));
  const request=async(body:unknown)=>{const r=await fetch("/api/v1/admin/garvex",{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf},body:JSON.stringify(body)});const t=await r.text();let j:any={};try{j=t?JSON.parse(t):{};}catch{throw new Error(`Invalid Garvex response (${r.status})`)}if(!r.ok)throw new Error(j?.error?.message??`Garvex failed (${r.status})`);return j.data;};
  const send=async(e?:FormEvent)=>{e?.preventDefault();const text=prompt.trim();if(!text||busy||!isPlatformAdmin)return;setMessages(x=>[...x,{id:id("u"),role:"user",content:text,mode}]);setPrompt("");setBusy(true);setError(null);setPhase(mode==="build"?"Inspecting project…":"Dispatching council…");setActivities([]);try{if(mode==="build"){if(!project)throw new Error("Select a project for Build & Fix. Chat and Research do not require a project.");const a=act("Inspect repository",`${project.name} · ${project.repoFullName}`);const r=await fetch(`/api/v1/projects/${project.id}/ai/editor`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf},body:JSON.stringify({mode:"prepare",prompt:text})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message??`Editor failed (${r.status})`);done(a,`${j.data.files?.length??0} relevant file(s) · ${j.data.baseSha?.slice(0,10)}`);setFiles(j.data.files??[]);const w=act("Write requested change","Only this explicit Build request can write to GitHub.");const p=await fetch(`/api/v1/projects/${project.id}/ai/editor`,{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf},body:JSON.stringify({mode:"apply",baseSha:j.data.baseSha,files:j.data.files,summary:j.data.summary})});const q=await p.json();if(!p.ok)throw new Error(q?.error?.message??`Apply failed (${p.status})`);done(w,`${q.data.branch} · ${q.data.commitSha?.slice(0,10)??"commit"}`);setPr(q.data.pullRequest??null);setTab("code");setMessages(x=>[...x,{id:id("a"),role:"assistant",content:`Done. I changed ${j.data.files?.length??0} file(s). ${q.data.pullRequest?`PR: ${q.data.pullRequest}`:""}`,mode:"build"}]);}else{const a=act("Dispatch council",`${configured} configured engine(s)`);const data=await request({prompt:text,mode,history:messages.map(m=>({role:m.role,content:m.content})).slice(-10),context:project?`Project ${project.name}; repository ${project.repoFullName}. Read-only context unless Build & Fix is explicitly selected.`:undefined,complex:true});done(a,`${data.workers?.length??0} agent(s) responded`);setWorkers(data.workers??[]);setFailed(data.failedWorkers??0);setTab("activity");setMessages(x=>[...x,{id:id("a"),role:"assistant",content:data.answer??"",mode}]);setPhase("Ready");}}catch(err){const m=err instanceof Error?err.message:String(err);setError(m);const a=act("Execution error",m,"error");done(a,m,"error");setPhase("Stopped");}finally{setBusy(false);requestAnimationFrame(()=>ta.current?.focus());}};
  const mediaRequest=async(kind:"image"|"video")=>{const text=prompt.trim() || (kind === "image" ? "Create a premium, cinematic website visual for this project, modern, editorial, high detail, no text." : "Create a premium 4-second cinematic website hero motion loop for this project, modern, editorial, smooth camera movement, no text.");if(busy||!isPlatformAdmin)return;setBusy(true);setError(null);setPhase(kind==="image"?"Generating image…":"Generating video…");setActivities([]);const a=act(kind==="image"?"Generate image":"Generate video","OpenRouter media pipeline");try{const r=await fetch("/api/v1/admin/garvex/media",{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf},body:JSON.stringify({kind,prompt:text,duration:4,resolution:"720p",aspectRatio:"16:9",generateAudio:true})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message??`Media request failed (${r.status})`);if(kind==="image"){setMedia({kind,url:j.data.image});setTab("preview");done(a,"Image ready");setPhase("Ready");}else{const jobId=j.data.job?.id;if(!jobId)throw new Error("Video job was not created");for(let i=0;i<48;i++){await new Promise(rf=>setTimeout(rf,2500));const p=await fetch(`/api/v1/admin/garvex/media?jobId=${encodeURIComponent(jobId)}`);const d=await p.json();const v=d.data?.video;const status=v?.status;if(status==="completed"){const u=v?.unsigned_urls?.[0]||v?.content_url;if(u){setMedia({kind:"video",url:u});setTab("preview");done(a,"Video ready");}break;}if(status==="failed"||status==="error")throw new Error("Video generation failed.");}}}catch(err){const m=err instanceof Error?err.message:String(err);setError(m);done(a,m,"error");}finally{setBusy(false);setPhase("Ready");}};
  const startVoice=async()=>{if(voice){recorder.current?.stop();setVoice(false);return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const r=new MediaRecorder(stream);recorder.current=r;r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setBusy(true);try{const f=new FormData();f.append("audio",new Blob(chunks.current,{type:r.mimeType||"audio/webm"}),"voice.webm");const res=await fetch("/api/v1/admin/garvex/voice",{method:"POST",headers:{"x-csrf-token":csrf},body:f});const j=await res.json();if(!res.ok)throw new Error(j?.error?.message??`Voice failed (${res.status})`);setMessages(x=>[...x,{id:id("u"),role:"user",content:j.data.transcript,mode:"chat"},{id:id("a"),role:"assistant",content:j.data.answer,mode:"chat"}]);if(j.data.audio)await new Audio(j.data.audio).play();}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setBusy(false);}};r.start();setVoice(true);}catch(err){setError(err instanceof Error?err.message:"Microphone access failed");}};
  const reset=()=>{setMessages([]);setActivities([]);setFiles([]);setMedia(null);setPr(null);setError(null);localStorage.removeItem("vo-garvex-history-max");};
  return <div className="garvex-shell garvex-v2"><div className="garvex-chat"><header className="garvex-topbar"><div className="garvex-brand"><div className="garvex-orb garvex-orb-live"><Orb3D size={58}/></div><div><div className="garvex-brand-title">Garvex<span>MAX</span></div><div className="garvex-brand-sub">{configured}/{providers.length} engines · {busy?phase:"Ready"}</div></div></div><div className="garvex-top-actions">{project?<span className="garvex-target">Target · {project.name}</span>:<span className="garvex-target">Global</span>}<button className="garvex-ghost" type="button" onClick={reset}>New chat</button><Link className="garvex-ghost" href="/admin/settings">Settings</Link></div></header>
  {credentialProblem.length>0?<div className="garvex-credential-banner"><div><strong>{credentialProblem.length} credential(s) need re-save</strong><span>The records exist in Platform Settings, but the current deployment cannot decrypt them. Keep <code>PLATFORM_ENCRYPTION_KEY</code> stable and re-save the affected keys.</span></div><Link href="/admin/settings">Fix credentials →</Link></div>:null}
  <main className="garvex-messages"><div className={messages.length===0?"garvex-welcome garvex-welcome-v2":"mx-auto w-full max-w-4xl px-4 py-8"}>{messages.length===0?<><div className="garvex-hero-orb"><Orb3D size={230}/><div className="garvex-orb-halo"/></div><div className="garvex-kicker">AUTONOMOUS ENGINEERING CONTROL</div><h1>Talk to Garvex.<br/><em>Build the thing.</em></h1><p>One control center for your repositories, deployments, AI agents and media pipelines.</p><div className="garvex-quick-actions"><button type="button" onClick={()=>{setMode("build");ta.current?.focus();}}><b>Build &amp; Fix</b><span>Write only on explicit request</span></button><button type="button" onClick={()=>{setMode("research");ta.current?.focus();}}><b>Research</b><span>Read-only multi-agent reasoning</span></button><button type="button" onClick={()=>void mediaRequest("image")} disabled={busy}><b>Image</b><span>Generate with OpenRouter</span></button><button type="button" onClick={()=>void mediaRequest("video")} disabled={busy}><b>Video</b><span>Generate with OpenRouter</span></button></div></>:messages.map(m=><div key={m.id} className={m.role==="user"?"mb-8 flex justify-end":"mb-10 flex items-start gap-3"}>{m.role==="assistant"?<div className="garvex-orb garvex-orb-sm"><Orb3D size={38}/></div>:null}<div className={m.role==="user"?"garvex-user-message":"garvex-assistant-message"} dir={arabic(m.content)?"rtl":"ltr"}>{m.role==="assistant"?<MessageResponse>{m.content}</MessageResponse>:<div className="whitespace-pre-wrap leading-7 text-[13px]">{m.content}</div>}</div></div>)}</div>{error?<div className="mx-auto w-full max-w-4xl px-4 pb-3"><div className="garvex-error">{error}</div></div>:null}</main>
  <footer className="garvex-composer-wrap"><div className="mx-auto w-full max-w-5xl px-4 pb-3"><div className="garvex-composer-tools"><label>Project<select className="input" value={selectedProjectId} onChange={e=>setSelectedProjectId(e.target.value)} disabled={busy}><option value="">Global — no project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.repoFullName}</option>)}</select></label><div className="garvex-media-tools"><button type="button" className="garvex-tool" disabled={busy} onClick={()=>void mediaRequest("image")}>◈ Image</button><button type="button" className="garvex-tool" disabled={busy} onClick={()=>void mediaRequest("video")}>◉ Video</button><button type="button" className={voice?"garvex-tool is-live":"garvex-tool"} disabled={busy} onClick={()=>void startVoice()}>{voice?"■ Stop voice":"◌ Live voice"}</button></div></div><form onSubmit={send} className="garvex-composer"><div className="garvex-mode-row"><div className="flex gap-1">{(["chat","build","research"] as const).map(x=><button type="button" key={x} className={mode===x?"garvex-mode active":"garvex-mode"} onClick={()=>setMode(x)}>{x==="chat"?"Chat":x==="build"?"Build & Fix":"Research"}</button>)}</div><span className="garvex-input-hint">Enter to send · Shift+Enter for line break</span></div><div className="garvex-input-row"><textarea ref={ta} className="garvex-textarea" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={mode==="build"?"Describe exactly what Garvex should change…":"Message Garvex…"} rows={1} disabled={busy||!isPlatformAdmin}/><button className="garvex-send" type="submit" disabled={!prompt.trim()||busy||!isPlatformAdmin}>↗</button></div></form><div className="garvex-footline"><span>GPU WebGL 3D</span><span>Adaptive refresh</span><span>Chat/Research read-only</span><span>Build writes only on request</span></div></div></footer></div>
  <aside className="garvex-live-panel garvex-live-v2"><div className="garvex-panel-head"><div><div className="garvex-panel-title">Live workspace</div><div className="hint">Agents · code · preview · runtime</div></div><span className="garvex-live-dot"/></div><div className="garvex-tabs">{(["activity","code","preview","files","terminal"] as WorkspaceTab[]).map(x=><button key={x} type="button" className={tab===x?"garvex-mode active":"garvex-mode"} onClick={()=>setTab(x)}>{x}</button>)}</div>{tab==="activity"?<div className="mt-3 space-y-2">{activities.length?activities.map(a=><div key={a.id} className="garvex-agent-row"><span className={a.status==="complete"?"garvex-agent-dot ready":a.status==="error"?"garvex-agent-dot error":"garvex-agent-dot"}/><div className="min-w-0 flex-1"><div className="text-[11px] font-medium">{a.label}</div><div className="text-[9px] text-muted-foreground">{a.detail}</div></div></div>):<div className="hint rounded-xl border border-dashed p-4">Waiting for an agent task…</div>}<div className="garvex-stats"><div><b>{workers.length}</b><span>agents</span></div><div><b>{failed}</b><span>failed</span></div><div><b>{files.length}</b><span>files</span></div></div></div>:tab==="code"?<div className="mt-3 space-y-3">{files.length?files.map(f=><div key={f.path} className="overflow-hidden rounded-xl border"><div className="mono border-b px-3 py-2 text-[10px]">{f.path}</div><pre className="max-h-[420px] overflow-auto p-3 text-[10px]" dir="ltr"><code>{f.content}</code></pre></div>):<div className="hint rounded-xl border border-dashed p-4">Build changes appear here.</div>}</div>:tab==="preview"?<div className="mt-3 space-y-3">{media?.kind==="image"?<img src={media.url} alt="Garvex generated" className="w-full rounded-xl border"/>:null}{media?.kind==="video"?<video src={media.url} controls playsInline className="w-full rounded-xl border"/>:null}{pr?<a className="underline text-sm" href={pr} target="_blank" rel="noreferrer">Open generated PR ↗</a>:project?<Link className="underline text-sm" href={`/projects/${project.id}/preview`}>Open project Live View ↗</Link>:<span className="hint">No project selected.</span>}</div>:tab==="files"?<div className="mt-3 space-y-1">{files.map(f=><div key={f.path} className="mono rounded-lg border px-3 py-2 text-[10px]">📄 {f.path}</div>)}</div>:<div className="mt-3 rounded-xl border bg-black/30 p-3 font-mono text-[10px]" dir="ltr"><div>$ garvex status</div><div>engines: {configured}/{providers.length}</div>{activities.map(a=><div key={a.id}>{a.status==="complete"?"✓":a.status==="error"?"✕":"›"} {a.label}: {a.detail}</div>)}</div>}<div className="garvex-provider-list">{providers.map(p=><ProviderPill key={p.provider} provider={p}/>)}</div></aside></div>;
}
